package pojo;
// Generated Dec 13, 2016 10:47:38 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "currency", catalog = "anytime_exchange")
public class Currency implements java.io.Serializable {

	private String currency;
	private BigDecimal transferMax;
	private BigDecimal transferLarge;

	public Currency() {
	}

	public Currency(String currency) {
		this.currency = currency;
	}

	public Currency(String currency, BigDecimal transferMax, BigDecimal transferLarge) {
		this.currency = currency;
		this.transferMax = transferMax;
		this.transferLarge = transferLarge;
	}

	@Id

	@Column(name = "currency", unique = true, nullable = false, length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "transfer_max", precision = 10)
	public BigDecimal getTransferMax() {
		return this.transferMax;
	}

	public void setTransferMax(BigDecimal transferMax) {
		this.transferMax = transferMax;
	}

	@Column(name = "transfer_large", precision = 10)
	public BigDecimal getTransferLarge() {
		return this.transferLarge;
	}

	public void setTransferLarge(BigDecimal transferLarge) {
		this.transferLarge = transferLarge;
	}

}
