package pojo;
// Generated Nov 15, 2017 2:30:26 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EBind generated by hbm2java
 */
@Entity
@Table(name = "e_bind", catalog = "anytime_exchange")
public class EBind implements java.io.Serializable {

	private int userId;
	private String happyLivesId;
	private String goldpayId;
	private String goldpayName;
	private String goldpayAcount;
	private String token;

	public EBind() {
	}

	public EBind(int userId) {
		this.userId = userId;
	}

	public EBind(int userId, String happyLivesId, String goldpayId, String goldpayName, String goldpayAcount,
			String token) {
		this.userId = userId;
		this.happyLivesId = happyLivesId;
		this.goldpayId = goldpayId;
		this.goldpayName = goldpayName;
		this.goldpayAcount = goldpayAcount;
		this.token = token;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "happy_lives_id", length = 20)
	public String getHappyLivesId() {
		return this.happyLivesId;
	}

	public void setHappyLivesId(String happyLivesId) {
		this.happyLivesId = happyLivesId;
	}

	@Column(name = "goldpay_id")
	public String getGoldpayId() {
		return this.goldpayId;
	}

	public void setGoldpayId(String goldpayId) {
		this.goldpayId = goldpayId;
	}

	@Column(name = "goldpay_name")
	public String getGoldpayName() {
		return this.goldpayName;
	}

	public void setGoldpayName(String goldpayName) {
		this.goldpayName = goldpayName;
	}

	@Column(name = "goldpay_acount")
	public String getGoldpayAcount() {
		return this.goldpayAcount;
	}

	public void setGoldpayAcount(String goldpayAcount) {
		this.goldpayAcount = goldpayAcount;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
