package pojo;
// Generated Jan 17, 2017 9:35:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ECrmUserInfo generated by hbm2java
 */
@Entity
@Table(name = "e_crm_user_info", catalog = "anytime_exchange")
public class ECrmUserInfo implements java.io.Serializable {

	private int userId;
	private String areaCode;
	private String userPhone;
	private String userName;
	private Integer userType;
	private Integer userAvailable;
	private BigDecimal userTotalAssets;
	private Date updateAt;

	public ECrmUserInfo() {
	}

	public ECrmUserInfo(int userId) {
		this.userId = userId;
	}

	public ECrmUserInfo(int userId, String areaCode, String userPhone, String userName, Integer userType,
			Integer userAvailable, BigDecimal userTotalAssets, Date updateAt) {
		this.userId = userId;
		this.areaCode = areaCode;
		this.userPhone = userPhone;
		this.userName = userName;
		this.userType = userType;
		this.userAvailable = userAvailable;
		this.userTotalAssets = userTotalAssets;
		this.updateAt = updateAt;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "area_code", length = 5)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "user_phone", length = 30)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_type")
	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	@Column(name = "user_available")
	public Integer getUserAvailable() {
		return this.userAvailable;
	}

	public void setUserAvailable(Integer userAvailable) {
		this.userAvailable = userAvailable;
	}

	@Column(name = "user_total_assets", precision = 20, scale = 4)
	public BigDecimal getUserTotalAssets() {
		return this.userTotalAssets;
	}

	public void setUserTotalAssets(BigDecimal userTotalAssets) {
		this.userTotalAssets = userTotalAssets;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 19)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

}
