package pojo;
// Generated Dec 19, 2017 12:22:01 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EUserConfig generated by hbm2java
 */
@Entity
@Table(name = "e_user_config", catalog = "anytime_exchange")
public class EUserConfig implements java.io.Serializable {

	private EUserConfigId id;

	public EUserConfig() {
	}

	public EUserConfig(EUserConfigId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", precision = 22, scale = 0)),
			@AttributeOverride(name = "userConfigValue", column = @Column(name = "user_config_value")) })
	public EUserConfigId getId() {
		return this.id;
	}

	public void setId(EUserConfigId id) {
		this.id = id;
	}

}
