package pojo;
// Generated Dec 14, 2017 3:09:15 PM by Hibernate Tools 5.2.6.Final

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EUserConfigId generated by hbm2java
 */
@Embeddable
public class EUserConfigId implements java.io.Serializable {

	private Double userId;
	private byte[] userConfigValue;

	public EUserConfigId() {
	}

	public EUserConfigId(Double userId, byte[] userConfigValue) {
		this.userId = userId;
		this.userConfigValue = userConfigValue;
	}

	@Column(name = "user_id", precision = 22, scale = 0)
	public Double getUserId() {
		return this.userId;
	}

	public void setUserId(Double userId) {
		this.userId = userId;
	}

	@Column(name = "user_config_value")
	public byte[] getUserConfigValue() {
		return this.userConfigValue;
	}

	public void setUserConfigValue(byte[] userConfigValue) {
		this.userConfigValue = userConfigValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EUserConfigId))
			return false;
		EUserConfigId castOther = (EUserConfigId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserConfigValue() == castOther.getUserConfigValue())
						|| (this.getUserConfigValue() != null && castOther.getUserConfigValue() != null
								&& Arrays.equals(this.getUserConfigValue(), castOther.getUserConfigValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserConfigValue() == null ? 0 : Arrays.hashCode(this.getUserConfigValue()));
		return result;
	}

}
