package pojo;
// Generated Jan 17, 2017 9:35:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EWallet generated by hbm2java
 */
@Entity
@Table(name = "e_wallet", catalog = "anytime_exchange")
public class EWallet implements java.io.Serializable {

	private Integer walletId;
	private ECurrency ECurrency;
	private int userId;
	private BigDecimal balance;
	private Date updateTime;

	public EWallet() {
	}

	public EWallet(ECurrency ECurrency, int userId, BigDecimal balance) {
		this.ECurrency = ECurrency;
		this.userId = userId;
		this.balance = balance;
	}

	public EWallet(ECurrency ECurrency, int userId, BigDecimal balance, Date updateTime) {
		this.ECurrency = ECurrency;
		this.userId = userId;
		this.balance = balance;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "wallet_id", unique = true, nullable = false)
	public Integer getWalletId() {
		return this.walletId;
	}

	public void setWalletId(Integer walletId) {
		this.walletId = walletId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "currency", nullable = false)
	public ECurrency getECurrency() {
		return this.ECurrency;
	}

	public void setECurrency(ECurrency ECurrency) {
		this.ECurrency = ECurrency;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "balance", nullable = false, precision = 20, scale = 4)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
