package pojo;
// Generated Mar 24, 2017 3:12:03 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EWithdraw generated by hbm2java
 */
@Entity
@Table(name = "e_withdraw", catalog = "test_exchange")
public class EWithdraw implements java.io.Serializable {

	private Integer withdrawId;
	private int userId;
	private String areaCode;
	private String userPhone;
	private String transferId;
	private int reviewStatus;
	private int goldpayRemit;

	public EWithdraw() {
	}

	public EWithdraw(int userId, String areaCode, String userPhone, String transferId, int reviewStatus,
			int goldpayRemit) {
		this.userId = userId;
		this.areaCode = areaCode;
		this.userPhone = userPhone;
		this.transferId = transferId;
		this.reviewStatus = reviewStatus;
		this.goldpayRemit = goldpayRemit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "withdraw_id", unique = true, nullable = false)
	public Integer getWithdrawId() {
		return this.withdrawId;
	}

	public void setWithdrawId(Integer withdrawId) {
		this.withdrawId = withdrawId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "area_code", nullable = false, length = 5)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "user_phone", nullable = false)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "transfer_id", nullable = false)
	public String getTransferId() {
		return this.transferId;
	}

	public void setTransferId(String transferId) {
		this.transferId = transferId;
	}

	@Column(name = "review_status", nullable = false)
	public int getReviewStatus() {
		return this.reviewStatus;
	}

	public void setReviewStatus(int reviewStatus) {
		this.reviewStatus = reviewStatus;
	}

	@Column(name = "goldpay_remit", nullable = false)
	public int getGoldpayRemit() {
		return this.goldpayRemit;
	}

	public void setGoldpayRemit(int goldpayRemit) {
		this.goldpayRemit = goldpayRemit;
	}

}
