package pojo;
// Generated Dec 13, 2016 10:47:38 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Friend generated by hbm2java
 */
@Entity
@Table(name = "friend", catalog = "anytime_exchange")
public class Friend implements java.io.Serializable {

	private Integer ufId;
	private User friendUser;
	private int userId;

	public Friend() {
	}

	public Friend(User friendUser, int userId) {
		this.friendUser = friendUser;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "uf_Id", unique = true, nullable = false)
	public Integer getUfId() {
		return this.ufId;
	}

	public void setUfId(Integer ufId) {
		this.ufId = ufId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "friend_Id", nullable = false)
	public User getFriendUser() {
		return this.friendUser;
	}

	public void setFriendUser(User friendUser) {
		this.friendUser = friendUser;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
