package pojo;
// Generated Nov 30, 2016 12:52:00 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "anytime_exchange")
public class Test implements java.io.Serializable {

	private long id;

	public Test() {
	}

	public Test(long id) {
		this.id = id;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

}
