package com.yuyutechnology.exchange.pojo;
// Generated Mar 24, 2017 3:12:03 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EBadAccount generated by hbm2java
 */
@Entity
@Table(name = "e_bad_account")
public class BadAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6945481260500703753L;
	private Integer badAccountId;
	private int userId;
	private String currency;
	private BigDecimal sumAmount;
	private BigDecimal balanceBefore;
	private BigDecimal balanceNow;
	private Date startTime;
	private Date endTime;
	private long startSeqId;
	private long endSeqId;
	private int badAccountStatus;

	public BadAccount() {
	}

	public BadAccount(int userId, String currency, BigDecimal sumAmount, BigDecimal balanceBefore,
			BigDecimal balanceNow, Date startTime, Date endTime, long startSeqId, long endSeqId, int badAccountStatus) {
		this.userId = userId;
		this.currency = currency;
		this.sumAmount = sumAmount;
		this.balanceBefore = balanceBefore;
		this.balanceNow = balanceNow;
		this.startTime = startTime;
		this.endTime = endTime;
		this.startSeqId = startSeqId;
		this.endSeqId = endSeqId;
		this.badAccountStatus = badAccountStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bad_account_id", unique = true, nullable = false)
	public Integer getBadAccountId() {
		return this.badAccountId;
	}

	public void setBadAccountId(Integer badAccountId) {
		this.badAccountId = badAccountId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "currency", nullable = false, length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "sum_amount", nullable = false, precision = 20, scale = 4)
	public BigDecimal getSumAmount() {
		return this.sumAmount;
	}

	public void setSumAmount(BigDecimal sumAmount) {
		this.sumAmount = sumAmount;
	}

	@Column(name = "balance_history", nullable = false, precision = 20, scale = 4)
	public BigDecimal getBalanceBefore() {
		return this.balanceBefore;
	}

	public void setBalanceBefore(BigDecimal balanceBefore) {
		this.balanceBefore = balanceBefore;
	}

	@Column(name = "balance_now", nullable = false, precision = 20, scale = 4)
	public BigDecimal getBalanceNow() {
		return this.balanceNow;
	}

	public void setBalanceNow(BigDecimal balanceNow) {
		this.balanceNow = balanceNow;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", nullable = false, length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
	
	@Column(name = "start_seq_id", nullable = false)
	public long getStartSeqId() {
		return this.startSeqId;
	}

	public void setStartSeqId(long startSeqId) {
		this.startSeqId = startSeqId;
	}

	@Column(name = "end_seq_id", nullable = false)
	public long getEndSeqId() {
		return this.endSeqId;
	}

	public void setEndSeqId(long endSeqId) {
		this.endSeqId = endSeqId;
	}

	@Column(name = "bad_account_status", nullable = false)
	public int getBadAccountStatus() {
		return this.badAccountStatus;
	}

	public void setBadAccountStatus(int badAccountStatus) {
		this.badAccountStatus = badAccountStatus;
	}

}
