package com.yuyutechnology.exchange.pojo;
// Generated Dec 17, 2016 2:05:54 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bind generated by hbm2java
 */
@Entity
@Table(name = "e_bind")
public class Bind implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -613686505426931292L;
	private Integer bindId;
	private int userId;
	private String goldpayId;
	private String goldpayName;
	private String goldpayAcount;
	private String token;

	public Bind() {
	}

	public Bind(int userId) {
		this.userId = userId;
	}

//	public Bind(int userId, String goldpayId, String goldpayName, String goldpayAcount, String token) {
//		this.userId = userId;
//		this.goldpayId = goldpayId;
//		this.goldpayName = goldpayName;
//		this.goldpayAcount = goldpayAcount;
//		this.token = token;
//	}

	public Bind(int userId, String goldpayId, String goldpayName, String goldpayAcount) {
		this.userId = userId;
		this.goldpayId = goldpayId;
		this.goldpayName = goldpayName;
		this.goldpayAcount = goldpayAcount;
		this.token = "";
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bind_id", unique = true, nullable = false)
	public Integer getBindId() {
		return this.bindId;
	}

	public void setBindId(Integer bindId) {
		this.bindId = bindId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "goldpay_id")
	public String getGoldpayId() {
		return this.goldpayId;
	}

	public void setGoldpayId(String goldpayId) {
		this.goldpayId = goldpayId;
	}

	@Column(name = "goldpay_name")
	public String getGoldpayName() {
		return this.goldpayName;
	}

	public void setGoldpayName(String goldpayName) {
		this.goldpayName = goldpayName;
	}

	@Column(name = "goldpay_acount")
	public String getGoldpayAcount() {
		return this.goldpayAcount;
	}

	public void setGoldpayAcount(String goldpayAcount) {
		this.goldpayAcount = goldpayAcount;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
