package com.yuyutechnology.exchange.pojo;
// Generated May 25, 2017 2:13:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ECrmLog generated by hbm2java
 */
@Entity
@Table(name = "e_crm_log", catalog = "anytime_exchange")
public class CrmLog implements java.io.Serializable {

	private Integer logId;
	private Integer adminId;
	private String adminName;
	private Date operateTime;
	private int operation;
	private String target;

	public CrmLog() {
	}

	public CrmLog(int adminId, String adminName, Date operateTime, int operation) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.operateTime = operateTime;
		this.operation = operation;
	}

	public CrmLog(int adminId, String adminName, Date operateTime, int operation, String target) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.operateTime = operateTime;
		this.operation = operation;
		this.target = target;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "admin_id", nullable = false)
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@Column(name = "admin_name", nullable = false)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "operate_time", nullable = false, length = 19)
	public Date getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	@Column(name = "operation", nullable = false)
	public int getOperation() {
		return this.operation;
	}

	public void setOperation(int operation) {
		this.operation = operation;
	}

	@Column(name = "target")
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

}
