package com.yuyutechnology.exchange.pojo;
// Generated Dec 15, 2016 8:56:30 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "currency")
public class Currency implements java.io.Serializable {

	@Override
	public String toString() {
		return "Currency [currency=" + currency + ", nameEn=" + nameEn + ", nameCn=" + nameCn + ", nameHk=" + nameHk
				+ ", currencyImage=" + currencyImage + ", currencyStatus=" + currencyStatus + ", transferMax="
				+ transferMax + ", transferLarge=" + transferLarge + ", assetThreshold=" + assetThreshold + ", wallets="
				+ wallets + "]";
	}

	private String currency;
	private String nameEn;
	private String nameCn;
	private String nameHk;
	private String currencyImage;
	private int currencyStatus;
	private BigDecimal transferMax;
	private BigDecimal transferLarge;
	private BigDecimal assetThreshold;
	private Set<Wallet> wallets = new HashSet<Wallet>(0);

	public Currency() {
	}

	public Currency(String currency, int currencyStatus) {
		this.currency = currency;
		this.currencyStatus = currencyStatus;
	}

	public Currency(String currency, String nameEn, String nameCn, String nameHk, String currencyImage,
			int currencyStatus, BigDecimal transferMax, BigDecimal transferLarge, BigDecimal assetThreshold,
			Set<Wallet> wallets) {
		this.currency = currency;
		this.nameEn = nameEn;
		this.nameCn = nameCn;
		this.nameHk = nameHk;
		this.currencyImage = currencyImage;
		this.currencyStatus = currencyStatus;
		this.transferMax = transferMax;
		this.transferLarge = transferLarge;
		this.assetThreshold = assetThreshold;
		this.wallets = wallets;
	}

	@Id

	@Column(name = "currency", unique = true, nullable = false, length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "name_en")
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "name_cn")
	public String getNameCn() {
		return this.nameCn;
	}

	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}

	@Column(name = "name_hk")
	public String getNameHk() {
		return this.nameHk;
	}

	public void setNameHk(String nameHk) {
		this.nameHk = nameHk;
	}

	@Column(name = "currency_image")
	public String getCurrencyImage() {
		return this.currencyImage;
	}

	public void setCurrencyImage(String currencyImage) {
		this.currencyImage = currencyImage;
	}

	@Column(name = "currency_status", nullable = false)
	public int getCurrencyStatus() {
		return this.currencyStatus;
	}

	public void setCurrencyStatus(int currencyStatus) {
		this.currencyStatus = currencyStatus;
	}

	@Column(name = "transfer_max", precision = 10)
	public BigDecimal getTransferMax() {
		return this.transferMax;
	}

	public void setTransferMax(BigDecimal transferMax) {
		this.transferMax = transferMax;
	}

	@Column(name = "transfer_large", precision = 10)
	public BigDecimal getTransferLarge() {
		return this.transferLarge;
	}

	public void setTransferLarge(BigDecimal transferLarge) {
		this.transferLarge = transferLarge;
	}

	@Column(name = "asset_threshold", precision = 10)
	public BigDecimal getAssetThreshold() {
		return this.assetThreshold;
	}

	public void setAssetThreshold(BigDecimal assetThreshold) {
		this.assetThreshold = assetThreshold;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currency")
	public Set<Wallet> getWallets() {
		return this.wallets;
	}

	public void setWallets(Set<Wallet> wallets) {
		this.wallets = wallets;
	}

}
