package com.yuyutechnology.exchange.pojo;
// Generated Dec 13, 2017 10:49:46 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**远程数据表只读不能写
 * GAccount generated by hbm2java 
 */
@Entity
@Table(name = "g_account" )
public class GoldpayAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4495682874419737529L;
	private long goldpayUserId;
	private Long balance;
	private String accountNum;

	public GoldpayAccount() {
	}

	public GoldpayAccount(long goldpayUserId) {
		this.goldpayUserId = goldpayUserId;
	}

	public GoldpayAccount(long goldpayUserId, Long balance, String accountNum) {
		this.goldpayUserId = goldpayUserId;
		this.balance = balance;
		this.accountNum = accountNum;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public long getGoldpayUserId() {
		return this.goldpayUserId;
	}

	public void setGoldpayUserId(long userId) {
		this.goldpayUserId = userId;
	}

	@Column(name = "balance")
	public Long getBalance() {
		return this.balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}

	@Column(name = "account_id", length = 12)
	public String getAccountNum() {
		return accountNum;
	}

	public void setAccountNum(String accountNum) {
		this.accountNum = accountNum;
	}
}
