package com.yuyutechnology.exchange.pojo;
// Generated Jan 16, 2017 11:03:59 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EUserConfig generated by hbm2java
 */
@Entity
@Table(name = "e_user_config")
public class UserConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8622107438592738094L;
	private Integer userId;
	private String userConfigValue;

	public UserConfig() {
	}

	public UserConfig(String userConfigValue) {
		this.userConfigValue = userConfigValue;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_config_value")
	public String getUserConfigValue() {
		return this.userConfigValue;
	}

	public void setUserConfigValue(String userConfigValue) {
		this.userConfigValue = userConfigValue;
	}

}
