package com.yuyutechnology.exchange.pojo;
// Generated Dec 17, 2016 2:05:54 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wallet generated by hbm2java
 */
@Entity
@Table(name = "e_wallet")
public class Wallet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8850503486784707445L;
	private Integer walletId;
	private Currency currency;
	private int userId;
	private BigDecimal balance;
	private Date updateTime;
	private Integer updateSeqId;

	public Wallet() {
	}

	public Wallet(Currency currency, int userId, BigDecimal balance) {
		this.currency = currency;
		this.userId = userId;
		this.balance = balance;
	}

	public Wallet(Currency currency, int userId, BigDecimal balance, Date updateTime,Integer updateSeqId) {
		this.currency = currency;
		this.userId = userId;
		this.balance = balance;
		this.updateTime = updateTime;
		this.updateSeqId = updateSeqId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "wallet_id", unique = true, nullable = false)
	public Integer getWalletId() {
		return this.walletId;
	}

	public void setWalletId(Integer walletId) {
		this.walletId = walletId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "currency", nullable = false)
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "balance", nullable = false, precision = 20, scale = 4)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_seq_id", nullable = false)
	public Integer getUpdateSeqId() {
		return updateSeqId;
	}

	public void setUpdateSeqId(Integer updateSeqId) {
		this.updateSeqId = updateSeqId;
	}
}
