package com.yuyutechnology.exchange.pojo;
// Generated Mar 7, 2017 9:58:38 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EWithdrawReview generated by hbm2java
 */
@Entity
@Table(name = "e_withdraw_review" )
public class WithdrawReview implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6005207210672582423L;
	private Integer withdrawId;
	private String transferId;
	private int reviewStatus;

	public WithdrawReview() {
	}

	public WithdrawReview(String transferId, int reviewStatus) {
		this.transferId = transferId;
		this.reviewStatus = reviewStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "withdraw_id", unique = true, nullable = false)
	public Integer getWithdrawId() {
		return this.withdrawId;
	}

	public void setWithdrawId(Integer withdrawId) {
		this.withdrawId = withdrawId;
	}

	@Column(name = "transfer_id", nullable = false)
	public String getTransferId() {
		return this.transferId;
	}

	public void setTransferId(String transferId) {
		this.transferId = transferId;
	}

	@Column(name = "review_status", nullable = false)
	public int getReviewStatus() {
		return this.reviewStatus;
	}

	public void setReviewStatus(int reviewStatus) {
		this.reviewStatus = reviewStatus;
	}

}
